
-- Add more countries to the countries table
INSERT INTO countries (name, code) VALUES
('Afghanistan', 'AF'),
('Albania', 'AL'),
('Algeria', 'DZ'),
('Argentina', 'AR'),
('Armenia', 'AM'),
('Austria', 'AT'),
('Azerbaijan', 'AZ'),
('Bahrain', 'BH'),
('Bangladesh', 'BD'),
('Belarus', 'BY'),
('Belgium', 'BE'),
('Bolivia', 'BO'),
('Bosnia and Herzegovina', 'BA'),
('Brazil', 'BR'),
('Bulgaria', 'BG'),
('Cambodia', 'KH'),
('Chile', 'CL'),
('China', 'CN'),
('Colombia', 'CO'),
('Costa Rica', 'CR'),
('Croatia', 'HR'),
('Czech Republic', 'CZ'),
('Denmark', 'DK'),
('Dominican Republic', 'DO'),
('Ecuador', 'EC'),
('Egypt', 'EG'),
('Estonia', 'EE'),
('Ethiopia', 'ET'),
('Finland', 'FI'),
('Georgia', 'GE'),
('Ghana', 'GH'),
('Greece', 'GR'),
('Guatemala', 'GT'),
('Honduras', 'HN'),
('Hong Kong', 'HK'),
('Hungary', 'HU'),
('Iceland', 'IS'),
('India', 'IN'),
('Indonesia', 'ID'),
('Iran', 'IR'),
('Iraq', 'IQ'),
('Ireland', 'IE'),
('Israel', 'IL'),
('Italy', 'IT'),
('Jamaica', 'JM'),
('Japan', 'JP'),
('Jordan', 'JO'),
('Kazakhstan', 'KZ'),
('Kenya', 'KE'),
('Kuwait', 'KW'),
('Latvia', 'LV'),
('Lebanon', 'LB'),
('Libya', 'LY'),
('Lithuania', 'LT'),
('Luxembourg', 'LU'),
('Malaysia', 'MY'),
('Mexico', 'MX'),
('Morocco', 'MA'),
('Myanmar', 'MM'),
('Nepal', 'NP'),
('New Zealand', 'NZ'),
('Nigeria', 'NG'),
('North Korea', 'KP'),
('Norway', 'NO'),
('Oman', 'OM'),
('Pakistan', 'PK'),
('Palestine', 'PS'),
('Panama', 'PA'),
('Peru', 'PE'),
('Philippines', 'PH'),
('Poland', 'PL'),
('Portugal', 'PT'),
('Qatar', 'QA'),
('Romania', 'RO'),
('Russia', 'RU'),
('Saudi Arabia', 'SA'),
('Serbia', 'RS'),
('Slovakia', 'SK'),
('Slovenia', 'SI'),
('South Africa', 'ZA'),
('South Korea', 'KR'),
('Spain', 'ES'),
('Sri Lanka', 'LK'),
('Syria', 'SY'),
('Taiwan', 'TW'),
('Thailand', 'TH'),
('Tunisia', 'TN'),
('Turkey', 'TR'),
('Ukraine', 'UA'),
('United Arab Emirates', 'AE'),
('Uruguay', 'UY'),
('Venezuela', 'VE'),
('Vietnam', 'VN'),
('Yemen', 'YE')
ON CONFLICT (code) DO NOTHING;
